content:
  - name: pages
    label: Pages
    type: collection
    path: content/*
    subfolders: true
    view:
      fields: [title, description, date]
      sort: [date, title]
    fields:
      - name: title
        required: true
        description: 'Title of the post'
        label: Title
        type: string
        
      - name: description
        required: true
        label: Description
        description: 'SEO Description for the post'
        type: text
        options:
          maxlength: 150
      
      - name: keywords
        label: Keywords
        type: string
        list:
          min: 1
          max: 5
          collapsible: false
      
      - name: draft
        required: true
        label: Draft
        type: boolean
      
      - name: slug
        required: true
        label: Slug
        type: string
      
      - name: date
        required: true
        label: Date
        type: date
      
      - name: categories
        required: true
        label: Category
        type: select
        options:
          values:
            - value: lower-primary
              label: Lower Primary
            
            - value: upper-primary
              label: Upper Primary
            
            - value: secondary
              label: Secondary
            
            - value: higher-secondary
              label: HS
            
            - value: ug
              label: UG
            
            - value: pg
              label: PG
            
            - value: diploma
              label: Diploma
            
            - value: teaching-course
              label: Teaching Course
            
            - value: competitive-exams
              label: Competitive Exams
            
            - value: skill-development
              label: Skill Development
            
            - value: doctorate
              label: Doctorate
            
            - value: research
              label: Research
      
      - name: readingTime
        label: Reading Time
        type: string
      
      - name: params
        required: true
        label: Params
        type: object
        
        fields:
          - name: author
            required: true
            label: Author
            type: string
            
          - name: chapter_title
            label: Chapter Title
            type: string
            
      - name: thumbnail
        required: true
        label: Thumbnail Image Url
        type: string
        
      - name: body
        required: true
        label: Body
        type: rich-text