content:
  - name: pages
    label: Pages
    type: collection
    path: content
    format: toml-frontmatter
    subfolders: true
    view:
      fields: [title, description, date]
      sort: [date, title]
    fields:
      - name: title
        required: true
        description: 'Title of the post'
        label: Title
        type: string
        
      - name: description
        required: true
        label: Description
        description: 'SEO Description for the post'
        type: text
        options:
          maxlength: 150
      
      - name: keywords
        label: Keywords
        type: string
        list:
          min: 1
          max: 5
          collapsible: false
      
      - name: draft
        required: true
        label: Draft
        type: boolean
      
      - name: slug
        required: true
        label: Slug
        type: string
      
      - name: date
        required: true
        label: Date
        type: date
          
      - name: readingTime
        label: Reading Time
        type: string
      
      - name: params
        required: true
        label: Params
        type: object
        
        fields:
          - name: author
            required: true
            label: Author
            type: string
            
          - name: chapter_title
            label: Chapter Title
            type: string
            
      - name: thumbnail
        required: true
        label: Thumbnail Image Url
        type: string
        
      - name: body
        required: true
        label: Body
        type: rich-text